
package bank.client.driver.soap.jaxws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IOException", targetNamespace = "http://soap.driver.server.bank/")
public class IOException_Exception
    extends Exception
{

    /**
     * 
     */
    private static final long serialVersionUID = 3225389068105749444L;
    
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IOException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IOException_Exception(String message, IOException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IOException_Exception(String message, IOException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: bank.client.driver.soap.jaxws.IOException
     */
    public IOException getFaultInfo() {
        return faultInfo;
    }

}
