
package bank.client.driver.soap.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapBankServiceImplService", targetNamespace = "http://soap.driver.server.bank/", wsdlLocation = "http://localhost:1111/hs?wsdl")
public class SoapBankServiceImplService
    extends Service
{

    private final static URL SOAPBANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPBANKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SOAPBANKSERVICEIMPLSERVICE_QNAME = new QName("http://soap.driver.server.bank/", "SoapBankServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1111/hs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPBANKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SOAPBANKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SoapBankServiceImplService() {
        super(__getWsdlLocation(), SOAPBANKSERVICEIMPLSERVICE_QNAME);
    }

    public SoapBankServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPBANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public SoapBankServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPBANKSERVICEIMPLSERVICE_QNAME);
    }

    public SoapBankServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPBANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public SoapBankServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapBankServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapBankServiceImpl
     */
    @WebEndpoint(name = "SoapBankServiceImplPort")
    public SoapBankServiceImpl getSoapBankServiceImplPort() {
        return super.getPort(new QName("http://soap.driver.server.bank/", "SoapBankServiceImplPort"), SoapBankServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapBankServiceImpl
     */
    @WebEndpoint(name = "SoapBankServiceImplPort")
    public SoapBankServiceImpl getSoapBankServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.driver.server.bank/", "SoapBankServiceImplPort"), SoapBankServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPBANKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPBANKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SOAPBANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
